In [15]:
from keras.datasets import mnist
from keras.utils import np_utils

# download the mnist to the path '~/.keras/datasets/' if it is the first time to be called
# X shape (60,000 28x28), y shape (10,000, )
(X_train, y_train), (X_test, y_test) = mnist.load_data()

print(X_train.shape)
print(y_train.shape)
print(type(X_train))
print(y_train[:3])
print(X_test.shape)

# data pre-processing
X_train = X_train.reshape(X_train.shape[0], -1) / 255.   # normalize
X_test = X_test.reshape(X_test.shape[0], -1) / 255.      # normalize
y_train = np_utils.to_categorical(y_train, num_classes=10)
y_test = np_utils.to_categorical(y_test, num_classes=10)

(60000, 28, 28)
(60000,)
<class 'numpy.ndarray'>
[5 0 4]
(10000, 28, 28)


In [13]:
print(X_train.shape)
print(y_train.shape)
print(type(X_train))
print(X_test.shape)

(60000, 784)
(60000, 10)
<class 'numpy.ndarray'>
(10000, 784)


In [4]:
print(y_train[:3])

[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


In [5]:
import numpy as np
np.random.seed(1337)  # for reproducibility
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import RMSprop

# 建立模型
model = Sequential([
    Dense(32, input_dim=784),
    Activation('relu'),
    Dense(10),
    Activation('softmax'),
])

# 优化器
rmsprop = RMSprop(lr=0.001, rho=0.9, epsilon=1e-08, decay=0.0)

In [6]:
# 激活模型
# We add metrics to get more results you want to see
model.compile(optimizer=rmsprop,
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [8]:
# 训练网络
print('Training ------------')
# Another way to train the model
model.fit(X_train, y_train, epochs=2, batch_size=32)

Training ------------
Epoch 1/2
60000/60000 [==============================] - 3s 58us/step - loss: 0.3434 - acc: 0.9045
Epoch 2/2
60000/60000 [==============================] - 3s 53us/step - loss: 0.1947 - acc: 0.9438


In [9]:
# 测试模型
print('\nTesting ------------')
# Evaluate the model with the metrics we defined earlier
loss, accuracy = model.evaluate(X_test, y_test)

print('test loss: ', loss)
print('test accuracy: ', accuracy)


Testing ------------
10000/10000 [==============================] - 0s 28us/step
test loss:  0.1738160644516349
test accuracy:  0.951
